import{S as w,i as p}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const u="44834659-67420821c74452072565be409",b=async e=>{try{const t=encodeURIComponent(e);return await axios.get(`https://pixabay.com/api/?key=${u}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=1`)}catch(t){throw console.log(t),new Error(t.message)}},L=async(e,t)=>{try{const a=encodeURIComponent(e),o=await axios.get(`https://pixabay.com/api/?key=${u}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`);if(o.data.hits.length===0)throw new Error;return o}catch(a){throw console.log(a),new Error("We're sorry, but you've reached the end of search results.")}},f=(e,t)=>{const a=e.map(o=>`<li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"/>
            </a>
            <ul class="info-summary">
                <li class="info-item"><h3 class="info-title">Likes</h3><p class="info-statistics">${o.likes}</p></li>
                <li class="info-item"><h3 class="info-title">Views</h3><p class="info-statistics">${o.views}</p></li>
                <li class="info-item"><h3 class="info-title">Comments</h3><p class="info-statistics">${o.comments}</p></li>
                <li class="info-item"><h3 class="info-title">Downloads</h3><p class="info-statistics">${o.downloads}</p></li>
            </ul>
        </li>`).join("");t.insertAdjacentHTML("beforeend",a)},$=document.querySelector(".form"),l=document.querySelector(".gallery"),n=document.querySelector(".loader"),i=document.querySelector(".load-more-btn"),m=new w(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250});let c="",h=1;const y=e=>{e.target.elements.search.value=""},E=e=>{e.innerHTML=""},g=e=>{e==="aboveGallery"?l.parentNode.insertBefore(n,l):e==="aboveLoadMore"&&i.parentNode.insertBefore(n,i),n.style.display="block"};$.addEventListener("submit",e=>{if(e.preventDefault(),g("aboveGallery"),i.style.display="block",c=e.target.elements.search.value.trim(),c.length<=0)return n.style.display="none",l.innerHTML="",y(e),i.style.display="none",p.error({title:"Error",message:"Search value is empty",position:"topRight"});b(c).then(t=>{if(n.style.display="none",t.data.totalHits===0)throw e.target.elements.search.value="",new Error("No images found");return E(l),f(t.data.hits,l),y(e),m.refresh(),c}).catch(t=>{i.style.display="none",n.style.display="none",console.error(t),p.error({title:"Error",message:`Sorry, there are no images matching your search query. Please try again! Error: ${t.message}`,position:"topRight"}),y(e),l.innerHTML=""})});i.addEventListener("click",()=>{h+=1,g("aboveLoadMore"),L(c,h).then(e=>{if(n.style.display="none",e.data.hits.length===0)throw new Error;f(e.data.hits,l),m.refresh()}).catch(e=>{console.log(e),i.style.display="none",n.style.display="none",p.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})})});
//# sourceMappingURL=commonHelpers.js.map
