import{S as L,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&r(p)}).observe(document,{childList:!0,subtree:!0});function a(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(s){if(s.ep)return;s.ep=!0;const o=a(s);fetch(s.href,o)}})();const h="44834659-67420821c74452072565be409",v=async e=>{try{const t=encodeURIComponent(e);return await axios.get(`https://pixabay.com/api/?key=${h}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=1`)}catch(t){return new Error(t.message)}},$=async(e,t)=>{try{const a=encodeURIComponent(e),r=await axios.get(`https://pixabay.com/api/?key=${h}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`);return r.data.hits.length===0?new Error:r}catch{return new Error}},m=async(e,t)=>{const a=e.map(r=>`<li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}"/>
            </a>
            <ul class="info-summary">
                <li class="info-item"><h3 class="info-title">Likes</h3><p class="info-statistics">${r.likes}</p></li>
                <li class="info-item"><h3 class="info-title">Views</h3><p class="info-statistics">${r.views}</p></li>
                <li class="info-item"><h3 class="info-title">Comments</h3><p class="info-statistics">${r.comments}</p></li>
                <li class="info-item"><h3 class="info-title">Downloads</h3><p class="info-statistics">${r.downloads}</p></li>
            </ul>
        </li>`).join("");t.insertAdjacentHTML("beforeend",a)},S=document.querySelector(".form"),l=document.querySelector(".gallery"),i=document.querySelector(".loader"),n=document.querySelector(".load-more-btn"),g=new L(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250});let y="",f=1;const b=15,d=e=>{e.target.elements.search.value=""},u=e=>{e.innerHTML=""},w=e=>{e==="aboveGallery"?l.parentNode.insertBefore(i,l):e==="aboveLoadMore"&&n.parentNode.insertBefore(i,n),i.style.display="block"};S.addEventListener("submit",async e=>{if(e.preventDefault(),w("aboveGallery"),n.style.display="block",y=e.target.elements.search.value.trim(),f=1,y.length<=0)return i.style.display="none",u(l),d(e),n.style.display="none",c.error({title:"Error",message:"Search value is empty",position:"topRight"});try{const t=await v(y);if(i.style.display="none",t.data.totalHits===0)throw e.target.elements.search.value="",new Error("No images found");u(l),await m(t.data.hits,l),d(e),g.refresh(),t.data.totalHits<=b&&(n.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.style.display="none",i.style.display="none",c.error({title:"Error",message:`Sorry, there are no images matching your search query. Please try again! Error: ${t.message}`,position:"topRight"}),d(e),u(l)}});n.addEventListener("click",async()=>{f+=1,w("aboveLoadMore");try{const e=await $(y,f);i.style.display="none";let t=e.data.hits.length;if(t>0){await m(e.data.hits,l);const a=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:a,behavior:"smooth"}),g.refresh()}t<b&&(n.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.style.display="none",i.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
